# Generated by Django 6.0.7 on 2026-07-11 09:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Court',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام زمین')),
                ('address', models.CharField(max_length=100, verbose_name='آدرس')),
                ('city', models.CharField(choices=[('تهران', 'تهران'), ('کرج', 'کرج'), ('تبریز', 'تبریز'), ('کیش', 'کیش'), ('اصفهان', 'اصفهان'), ('شیراز', 'شیراز'), ('قزوین', 'قزوین'), ('مرکزی', 'مرکزی')], db_index=True, default='تهران', verbose_name='شهر')),
                ('max_players', models.IntegerField(verbose_name='تعداد بازیکنان مجاز')),
                ('base_price_per_hour', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='قیمت پایه برای هر ساعت')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='فعال یا غیرفعال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ آخرین به روز رسانی')),
                ('court_type', models.CharField(choices=[('PADDLE', 'پدل'), ('TENNIS', 'تنیس')], default='PADDLE', max_length=10, verbose_name='نوع زمین')),
            ],
            options={
                'verbose_name_plural': 'زمین ها',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام امکانات')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
            ],
            options={
                'verbose_name_plural': 'امکانات',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CourtImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='', verbose_name='تصویر')),
                ('is_primary', models.BooleanField(default=False, verbose_name='اصلی یا دیگر')),
                ('upload_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ آپلود')),
                ('court', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='courts.court', verbose_name='زمین')),
            ],
            options={
                'verbose_name_plural': 'تصاویر زمین',
                'ordering': ['is_primary'],
            },
        ),
        migrations.AddField(
            model_name='court',
            name='facilities',
            field=models.ManyToManyField(blank=True, to='courts.facility', verbose_name='کارت ها'),
        ),
        migrations.CreateModel(
            name='BlockedSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, verbose_name='تاریخ')),
                ('start_time', models.TimeField(verbose_name='زمان شروع')),
                ('end_time', models.TimeField(verbose_name='زمان پایان')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='فعال یا غیرفعال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ آخرین به روز رسانی')),
                ('court', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocked_slots', to='courts.court', verbose_name='زمین')),
            ],
            options={
                'verbose_name': 'بازه مسدود',
                'verbose_name_plural': 'بازه های مسدود',
                'ordering': ['court', 'date', 'start_time'],
                'unique_together': {('court', 'date', 'start_time', 'end_time')},
            },
        ),
        migrations.CreateModel(
            name='CourtPricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_price_per_hour', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='قیمت پایه برای هر ساعت')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='فعال یا غیرفعال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ آخرین به روز رسانی')),
                ('pricing_type', models.CharField(choices=[('WEEKDAY', 'روز های عادی'), ('WEEKEND', 'آخر هفته'), ('SPECIAL', 'مناسبات خاص'), ('HOLIDAY', 'تعطیلات')], default='WEEKDAY', max_length=10, verbose_name='نوع قیمت گذاری')),
                ('court', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pricing', to='courts.court', verbose_name='زمین')),
            ],
            options={
                'verbose_name_plural': 'قیمت های زمین',
                'ordering': ['court'],
                'unique_together': {('court', 'pricing_type')},
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(0, 'شنبه'), (1, 'یکشنبه'), (2, 'دوشنبه'), (3, 'سه شنبه'), (4, 'چهارشنبه'), (5, 'پنجشنبه'), (6, 'جمعه')], db_index=True, verbose_name='روز')),
                ('start_time', models.TimeField(verbose_name='زمان شروع')),
                ('end_time', models.TimeField(verbose_name='زمان پایان')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='فعال یا غیرفعال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ آخرین به روز رسانی')),
                ('court', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='courts.court', verbose_name='زمین')),
            ],
            options={
                'verbose_name_plural': 'زمان\u200cها',
                'ordering': ['court', 'day_of_week', 'start_time'],
                'unique_together': {('court', 'day_of_week', 'start_time', 'end_time')},
            },
        ),
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField(verbose_name='زمان شروع')),
                ('end_time', models.TimeField(verbose_name='زمان پایان')),
                ('status', models.CharField(choices=[('AVAILABLE', 'آزاد'), ('RESERVED', 'رزرو شده'), ('BLOCKED', 'مسدود'), ('EXPIRED', 'منقضی شده')], db_index=True, default='AVAILABLE', max_length=10, verbose_name='وضعیت')),
                ('date', models.DateField(db_index=True, verbose_name='تاریخ')),
                ('special_price', models.DecimalField(blank=True, decimal_places=2, help_text='در صورت خالی بودن، قیمت پایه زمین استفاده می\u200cشود', max_digits=10, null=True, verbose_name='قیمت ویژه')),
                ('court', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_slots', to='courts.court', verbose_name='زمین')),
            ],
            options={
                'verbose_name_plural': 'اسلات های زمانی',
                'ordering': ['court', 'date', 'start_time'],
                'unique_together': {('court', 'date', 'start_time', 'end_time')},
            },
        ),
    ]
