# Generated by Django 6.0.7 on 2026-07-11 10:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courts', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='blockedslot',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='courtpricing',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='schedule',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='timeslot',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='courtimage',
            name='upload_at',
        ),
        migrations.AddField(
            model_name='courtimage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2026, 7, 11, 10, 21, 10, 512079, tzinfo=datetime.timezone.utc), verbose_name='تاریخ ایجاد'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='courtimage',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='تاریخ آخرین به روز رسانی'),
        ),
        migrations.AddField(
            model_name='courtpricing',
            name='price_multiplier',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=10, verbose_name='مقیاس قیمت'),
        ),
        migrations.AddField(
            model_name='timeslot',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2026, 7, 11, 10, 22, 0, 124429, tzinfo=datetime.timezone.utc), verbose_name='تاریخ ایجاد'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='timeslot',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='تاریخ آخرین به روز رسانی'),
        ),
        migrations.AlterField(
            model_name='courtimage',
            name='image',
            field=models.ImageField(upload_to='court_images/%Y/%m/%d/', verbose_name='تصویر'),
        ),
        migrations.AddConstraint(
            model_name='blockedslot',
            constraint=models.UniqueConstraint(fields=('court', 'date', 'start_time', 'end_time'), name='unique_blocked_slot_court_date_time'),
        ),
        migrations.AddConstraint(
            model_name='courtpricing',
            constraint=models.UniqueConstraint(fields=('court', 'pricing_type'), name='unique_courtpricing_court_type'),
        ),
        migrations.AddConstraint(
            model_name='schedule',
            constraint=models.UniqueConstraint(fields=('court', 'day_of_week', 'start_time', 'end_time'), name='unique_schedule'),
        ),
        migrations.AddConstraint(
            model_name='timeslot',
            constraint=models.UniqueConstraint(fields=('court', 'date', 'start_time', 'end_time'), name='unique_timeslot_court_date_time'),
        ),
        migrations.RemoveField(
            model_name='courtpricing',
            name='base_price_per_hour',
        ),
    ]
