# Generated by Django 6.0.7 on 2026-07-11 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courts', '0002_alter_blockedslot_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='timeslot',
            options={'ordering': ['court', 'date', 'start_time'], 'verbose_name': 'بازه زمانی', 'verbose_name_plural': 'بازه های زمانی'},
        ),
    ]
