# Generated by Django 6.0.7 on 2026-07-20 15:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Reservations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='مبلغ')),
                ('status', models.CharField(choices=[('PENDING', 'در انتظار'), ('PAID', 'پرداخت شده'), ('FAILED', 'ناموفق'), ('REFUNDED', 'برگشت داده شده')], default='PENDING', max_length=20, verbose_name='وضعیت')),
                ('tracking_code', models.CharField(blank=True, max_length=100, verbose_name='کد پیگیری')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Reservations.reservation', verbose_name='رزرو')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
        ),
    ]
