# Generated by Django 6.0.7 on 2026-07-20 12:15

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courts', '0003_alter_timeslot_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='قیمت کل')),
                ('players_count', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(8)], verbose_name='تعداد بازیکنان')),
                ('status', models.CharField(choices=[('PENDING', 'در انتظار'), ('CONFIRMED', 'تایید شده'), ('CANCELLED', 'لغو شده'), ('COMPLETED', 'تکمیل شده')], db_index=True, default='PENDING', max_length=20, verbose_name='وضعیت')),
                ('is_paid', models.BooleanField(default=False, verbose_name='پرداخت شده')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('court', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='courts.court', verbose_name='زمین')),
                ('slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='courts.timeslot', verbose_name='اسلات')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name_plural': 'رزروها',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('user', 'court', 'slot'), name='unique_reservation_user_court_slot')],
            },
        ),
    ]
